/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BasicIdentityPanel.java
 *
 * Created on Apr 22, 2009, 11:15:31 AM
 */

package com.smartitengineering.ui.component;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author modhu7
 */
public class BasicIdentityPanel extends javax.swing.JPanel {
    private String nameOfInformationText;

    /** Creates new form BasicIdentityPanel */
    public BasicIdentityPanel() {
        initComponents();
    }

    public BasicIdentityPanel(String nameOfInformationText) {
        this.nameOfInformationText = nameOfInformationText;
        initComponents();
    }
    

    public JLabel getNameOfInformationLabel() {
        return nameOfInformationLabel;
    }

    public void setNameOfInformationLabel(JLabel nameOfInformationLabel) {
        this.nameOfInformationLabel = nameOfInformationLabel;
    }

    public NamePanel getNamePanel() {
        return namePanel;
    }

    public void setNamePanel(NamePanel namePanel) {
        this.namePanel = namePanel;
    }

    public JLabel getNationalIdLabel() {
        return nationalIdLabel;
    }

    public void setNationalIdLabel(JLabel nationalIdLabel) {
        this.nationalIdLabel = nationalIdLabel;
    }

    public JTextField getNationalIdTextField() {
        return nationalIdTextField;
    }

    public void setNationalIdTextField(JTextField nationalIdTextField) {
        this.nationalIdTextField = nationalIdTextField;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePanel = new com.smartitengineering.ui.component.NamePanel();
        nameOfInformationLabel = new javax.swing.JLabel();
        nationalIdLabel = new javax.swing.JLabel();
        nationalIdTextField = new javax.swing.JTextField();

        setFont(getFont());

        namePanel.setFont(namePanel.getFont());

        nameOfInformationLabel.setFont(nameOfInformationLabel.getFont().deriveFont(nameOfInformationLabel.getFont().getStyle() | java.awt.Font.BOLD));
        nameOfInformationLabel.setText("Information");

        nationalIdLabel.setFont(nationalIdLabel.getFont());
        nationalIdLabel.setText("Natioal ID");

        nationalIdTextField.setFont(nationalIdTextField.getFont());

        nameOfInformationLabel.setText(nameOfInformationText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameOfInformationLabel)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(nationalIdLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nationalIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(namePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameOfInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationalIdLabel)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameOfInformationLabel;
    private com.smartitengineering.ui.component.NamePanel namePanel;
    private javax.swing.JLabel nationalIdLabel;
    private javax.swing.JTextField nationalIdTextField;
    // End of variables declaration//GEN-END:variables

}
