package com.smartitengineering.ui.component;

import java.util.Calendar;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DatePanel.java
 *
 * Created on Apr 25, 2009, 7:10:06 PM
 */
/**
 *
 * @author modhu7
 */
public class DatePanel extends javax.swing.JPanel {

    private Vector<String> years = new Vector<String>();
    private Vector<String> months = new Vector<String>();

    /** Creates new form DatePanel */
    public DatePanel() {
        initComponents();
        setYears();
        setMonths();
        setDays(31);
    }

    public DatePanel(String textDateLabel) {
        this();
        dateLabel.setText(textDateLabel);
    }

    private boolean isLeapYear(Integer intYear) {
        if (intYear % 400 == 0) {
            return true;
        } else if (intYear % 100 == 0) {
            return false;
        } else if (intYear % 4 == 0) {
            return true;
        } else {
            return false;
        }
    }

    private boolean isNumber(String stringYear) {
        for (int i = 0; i < stringYear.length(); i++) {
            if (!Character.isDigit(stringYear.charAt(i))) {
                return false;
            }
        }
        return true;
    }

    private void setDays(int n) {
        Vector<String> days = new Vector<String>();
        days.add("Day");
        for (int i = 1; i <= n; i++) {
            Integer day = new Integer(i);
            days.add(day.toString());
            dayComboBox.setModel(new DefaultComboBoxModel(days.toArray()));
        }
    }

    private void setMonths() {
        months.add("Month");
        months.add("January");
        months.add("February");
        months.add("March");
        months.add("April");
        months.add("May");
        months.add("June");
        months.add("July");
        months.add("August");
        months.add("September");
        months.add("October");
        months.add("November");
        months.add("December");
        monthComboBox.setModel(new DefaultComboBoxModel(months.toArray()));
    }

    private void setYears() {
        years.add("Year");
        Calendar calendar = Calendar.getInstance();
        for (int i = 1930; i < calendar.get(Calendar.YEAR); i++) {
            Integer year = new Integer(i);
            years.add(year.toString());
        }
        yearComboBox.setModel(new DefaultComboBoxModel(years.toArray()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabel = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox();
        monthComboBox = new javax.swing.JComboBox();
        dayComboBox = new javax.swing.JComboBox();

        setFont(getFont());

        dateLabel.setFont(dateLabel.getFont());
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/smartitengineering/ui/component/Bundle"); // NOI18N
        dateLabel.setText(bundle.getString("DatePanel.dateLabel.text")); // NOI18N

        yearComboBox.setFont(yearComboBox.getFont());
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        yearComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearComboBoxItemStateChanged(evt);
            }
        });

        monthComboBox.setFont(monthComboBox.getFont());
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        monthComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthComboBoxItemStateChanged(evt);
            }
        });

        dayComboBox.setFont(dayComboBox.getFont());
        dayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel)
                .addGap(18, 18, 18)
                .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthComboBox, 0, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dateLabel)
                .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yearComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearComboBoxItemStateChanged
        // TODO add your handling code here:
        String stringYear = evt.getItem().toString();
        if (isNumber(stringYear)) {
            Integer intYear = new Integer(evt.getItem().toString());
            System.out.println(evt.getItem().toString());
            if (monthComboBox.getSelectedItem().toString().equalsIgnoreCase("February")) {
                if (isLeapYear(intYear))  {
                    setDays(29);
                } else {
                    setDays(28);
                }
            }
        }
    }//GEN-LAST:event_yearComboBoxItemStateChanged

    private void monthComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthComboBoxItemStateChanged
        // TODO add your handling code here:
        String year = yearComboBox.getSelectedItem().toString();
        String stringMonth = evt.getItem().toString();
        if (stringMonth.equalsIgnoreCase("April") || stringMonth.equalsIgnoreCase("June") || stringMonth.equalsIgnoreCase("September") || stringMonth.equalsIgnoreCase("November")) {
            setDays(30);
        } else if (stringMonth.equalsIgnoreCase("February")) {
            if (isNumber(year)) {
                Integer intYear = new Integer(year);
                if (isLeapYear(intYear)) {
                    setDays(29);
                } else {
                    setDays(28);
                }

            }
        } else {
            setDays(31);
        }
    }//GEN-LAST:event_monthComboBoxItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox dayComboBox;
    private javax.swing.JComboBox monthComboBox;
    private javax.swing.JComboBox yearComboBox;
    // End of variables declaration//GEN-END:variables

    public JLabel getDateLabel() {
        return dateLabel;
    }

    public void setDateLabel(JLabel dateLabel) {
        this.dateLabel = dateLabel;
    }

    public JComboBox getDayComboBox() {
        return dayComboBox;
    }

    public void setDayComboBox(JComboBox dayComboBox) {
        this.dayComboBox = dayComboBox;
    }

    public JComboBox getMonthComboBox() {
        return monthComboBox;
    }

    public void setMonthComboBox(JComboBox monthComboBox) {
        this.monthComboBox = monthComboBox;
    }

    public JComboBox getYearComboBox() {
        return yearComboBox;
    }

    public void setYearComboBox(JComboBox yearComboBox) {
        this.yearComboBox = yearComboBox;
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        DatePanel panel = new DatePanel();
        frame.add(panel);
        frame.setVisible(true);
    }
}
