/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserInformationPanel.java
 *
 * Created on Apr 22, 2009, 6:40:41 PM
 */

package com.smartitengineering.ui.component;

import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author modhu7
 */
public class UserInformationPanel extends javax.swing.JPanel {

    /** Creates new form UserInformationPanel */
    public UserInformationPanel() {
        initComponents();
    }

    public JLabel getEmailAddressLabel() {
        return emailAddressLabel;
    }

    public void setEmailAddressLabel(JLabel emailAddressLabel) {
        this.emailAddressLabel = emailAddressLabel;
    }

    public JTextField getEmailAddressTextField() {
        return emailAddressTextField;
    }

    public void setEmailAddressTextField(JTextField emailAddressTextField) {
        this.emailAddressTextField = emailAddressTextField;
    }

    public JLabel getNameOfInformationLabel() {
        return nameOfInformationLabel;
    }

    public void setNameOfInformationLabel(JLabel nameOfInformationLabel) {
        this.nameOfInformationLabel = nameOfInformationLabel;
    }

    public JLabel getNationalIdLabel3() {
        return nationalIdLabel3;
    }

    public void setNationalIdLabel3(JLabel nationalIdLabel3) {
        this.nationalIdLabel3 = nationalIdLabel3;
    }

    public JPasswordField getPasswordField() {
        return passwordField;
    }

    public void setPasswordField(JPasswordField passwordField) {
        this.passwordField = passwordField;
    }

    public JLabel getPasswordLabel() {
        return passwordLabel;
    }

    public void setPasswordLabel(JLabel passwordLabel) {
        this.passwordLabel = passwordLabel;
    }

    public JPasswordField getRePasswordField() {
        return rePasswordField;
    }

    public void setRePasswordField(JPasswordField rePasswordField) {
        this.rePasswordField = rePasswordField;
    }

    public JLabel getUsernameLabel() {
        return usernameLabel;
    }

    public void setUsernameLabel(JLabel usernameLabel) {
        this.usernameLabel = usernameLabel;
    }

    public JTextField getUsernameTextField() {
        return usernameTextField;
    }

    public void setUsernameTextField(JTextField usernameTextField) {
        this.usernameTextField = usernameTextField;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameOfInformationLabel = new javax.swing.JLabel();
        emailAddressLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nationalIdLabel3 = new javax.swing.JLabel();
        emailAddressTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        rePasswordField = new javax.swing.JPasswordField();

        setFont(getFont());

        nameOfInformationLabel.setFont(nameOfInformationLabel.getFont().deriveFont(nameOfInformationLabel.getFont().getStyle() | java.awt.Font.BOLD));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/smartitengineering/ui/component/Bundle"); // NOI18N
        nameOfInformationLabel.setText(bundle.getString("UserInformationPanel.nameOfInformationLabel.text")); // NOI18N

        emailAddressLabel.setFont(emailAddressLabel.getFont());
        emailAddressLabel.setText(bundle.getString("UserInformationPanel.emailAddressLabel.text")); // NOI18N

        usernameLabel.setFont(usernameLabel.getFont());
        usernameLabel.setText(bundle.getString("UserInformationPanel.usernameLabel.text")); // NOI18N

        passwordLabel.setFont(passwordLabel.getFont());
        passwordLabel.setText(bundle.getString("UserInformationPanel.passwordLabel.text")); // NOI18N

        nationalIdLabel3.setFont(nationalIdLabel3.getFont());
        nationalIdLabel3.setText(bundle.getString("UserInformationPanel.nationalIdLabel3.text")); // NOI18N

        emailAddressTextField.setFont(emailAddressTextField.getFont());
        emailAddressTextField.setText(bundle.getString("UserInformationPanel.emailAddressTextField.text")); // NOI18N

        usernameTextField.setFont(usernameTextField.getFont());
        usernameTextField.setText(bundle.getString("UserInformationPanel.usernameTextField.text")); // NOI18N

        passwordField.setFont(passwordField.getFont());
        passwordField.setText(bundle.getString("UserInformationPanel.passwordField.text")); // NOI18N

        rePasswordField.setFont(rePasswordField.getFont());
        rePasswordField.setText(bundle.getString("UserInformationPanel.rePasswordField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameOfInformationLabel)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nationalIdLabel3)
                    .addComponent(passwordLabel)
                    .addComponent(usernameLabel)
                    .addComponent(emailAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailAddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(usernameTextField)
                    .addComponent(passwordField)
                    .addComponent(rePasswordField)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameOfInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalIdLabel3)
                    .addComponent(emailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddressLabel)
                    .addComponent(rePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailAddressLabel;
    private javax.swing.JTextField emailAddressTextField;
    private javax.swing.JLabel nameOfInformationLabel;
    private javax.swing.JLabel nationalIdLabel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField rePasswordField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

}
